//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameGK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public string P_Username { get; set; }
        public string P_Password { get; set; }
        public Nullable<int> P_Score { get; set; }
        public Nullable<bool> P_State { get; set; }
    }
}
